version: 2.1
jobs:
  build-and-push:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo 'DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME'
      - run: echo 'DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD'
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Push Docker images
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
            docker tag  udagram-api-feed backenddocker2022/udagram-api-feed:v1
            docker tag  udagram-api-user backenddocker2022/udagram-api-user:v1
            docker tag  udagram-frontend:local backenddocker2022/udagram-frontend:v1
            docker tag  reverseproxy backenddocker2022/reverseproxy:v1
            docker push backenddocker2022/udagram-api-feed:v1
            docker push backenddocker2022/udagram-api-user:v1
            docker push backenddocker2022/udagram-frontend:v6
            docker push backenddocker2022/reverseproxy:v1
          environment:
            DOCKER_BUILDKIT: 1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-push
